version: "3"

services:
  glassfish:
    build: .
    ports:
      - 8080:8080
      - 4848:4848
    links: 
      - mysql:mysql
  mysql:
    build:
      context: ./mysql
    ports:
      - 3306:3306
    volumes: 
      - /var/data/foodimysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: seppo
    restart: always
