version: "3"

services:
  glassfish:
    build: .
    ports:
      - 8080:8080
    links: 
      - mysql:mysql
  mysql:
    build:
      context: ./mysql
    ports:
      - 3306:3306
    volumes: 
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment: 
      MYSQL_USER: root
      MYSQL_PASSWORD: seppo
    restart: always
